# Generated by Django 5.2.14 on 2026-05-15 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='club_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='fitness_level',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('elite', 'Elite')], default='beginner', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='onboarding_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('coach', 'Coach'), ('athlete', 'Athlete')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='sport',
            field=models.CharField(choices=[('swimming', 'Swimming'), ('triathlon', 'Triathlon'), ('open_water', 'Open Water')], default='swimming', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='stroke_specialty',
            field=models.CharField(choices=[('freestyle', 'Freestyle'), ('backstroke', 'Backstroke'), ('breaststroke', 'Breaststroke'), ('butterfly', 'Butterfly'), ('im', 'Individual Medley'), ('none', 'None')], default='none', max_length=20),
        ),
    ]
