# Generated by Django 5.2.14 on 2026-05-17 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insights', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='aiinsight',
            new_name='ai_insights_athlete_c08082_idx',
            old_name='ai_insights_athlete_type_created_idx',
        ),
        migrations.RenameIndex(
            model_name='aiinsight',
            new_name='ai_insights_athlete_09481e_idx',
            old_name='ai_insights_athlete_read_idx',
        ),
    ]
