# Generated by Django 5.2.14 on 2026-05-15 12:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('week_number', models.PositiveIntegerField()),
                ('day_of_week', models.IntegerField()),
                ('session_type', models.CharField(choices=[('warm_up', 'Warm Up'), ('drill', 'Drill'), ('threshold', 'Threshold'), ('intervals', 'Intervals'), ('race_pace', 'Race Pace'), ('recovery', 'Recovery'), ('open_water', 'Open Water')], default='intervals', max_length=20)),
                ('estimated_duration_min', models.PositiveIntegerField(blank=True, null=True)),
                ('coach_notes', models.TextField(blank=True, null=True)),
                ('order_in_day', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'sessions',
                'ordering': ['week_number', 'day_of_week', 'order_in_day'],
            },
        ),
        migrations.CreateModel(
            name='SessionSet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('set_type', models.CharField(choices=[('warm_up', 'Warm Up'), ('main', 'Main'), ('drill', 'Drill'), ('kick', 'Kick'), ('pull', 'Pull'), ('cool_down', 'Cool Down'), ('rest', 'Rest')], default='main', max_length=20)),
                ('repetitions', models.PositiveIntegerField(default=1)),
                ('distance_m', models.PositiveIntegerField(blank=True, null=True)),
                ('stroke', models.CharField(choices=[('freestyle', 'Freestyle'), ('backstroke', 'Backstroke'), ('breaststroke', 'Breaststroke'), ('butterfly', 'Butterfly'), ('im', 'Individual Medley'), ('choice', 'Choice')], default='freestyle', max_length=20)),
                ('equipment', models.JSONField(blank=True, default=list)),
                ('rest_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('send_off_interval', models.CharField(blank=True, max_length=10, null=True)),
                ('target_pace_per_100m', models.CharField(blank=True, max_length=10, null=True)),
                ('target_hr_zone', models.IntegerField(blank=True, null=True)),
                ('target_hr_bpm', models.IntegerField(blank=True, null=True)),
                ('intensity_rpe', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('video_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sets', to='plans.session')),
            ],
            options={
                'db_table': 'session_sets',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SetLibraryItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('set_type', models.CharField(choices=[('warm_up', 'Warm Up'), ('main', 'Main'), ('drill', 'Drill'), ('kick', 'Kick'), ('pull', 'Pull'), ('cool_down', 'Cool Down'), ('rest', 'Rest')], default='main', max_length=20)),
                ('repetitions', models.PositiveIntegerField(default=1)),
                ('distance_m', models.PositiveIntegerField(blank=True, null=True)),
                ('stroke', models.CharField(choices=[('freestyle', 'Freestyle'), ('backstroke', 'Backstroke'), ('breaststroke', 'Breaststroke'), ('butterfly', 'Butterfly'), ('im', 'Individual Medley'), ('choice', 'Choice')], default='freestyle', max_length=20)),
                ('equipment', models.JSONField(blank=True, default=list)),
                ('rest_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('send_off_interval', models.CharField(blank=True, max_length=10, null=True)),
                ('target_pace_per_100m', models.CharField(blank=True, max_length=10, null=True)),
                ('target_hr_zone', models.IntegerField(blank=True, null=True)),
                ('target_hr_bpm', models.IntegerField(blank=True, null=True)),
                ('intensity_rpe', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='set_library', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'set_library_items',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TrainingPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('duration_weeks', models.PositiveIntegerField(default=1)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('moderate', 'Moderate'), ('hard', 'Hard'), ('race_pace', 'Race Pace')], default='moderate', max_length=20)),
                ('sport', models.CharField(choices=[('swimming', 'Swimming'), ('triathlon', 'Triathlon'), ('open_water', 'Open Water')], default='swimming', max_length=20)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('is_template', models.BooleanField(default=False)),
                ('is_archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cloned_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clones', to='plans.trainingplan')),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'training_plans',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='session',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='plans.trainingplan'),
        ),
        migrations.CreateModel(
            name='PlanAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('custom_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_plans', to=settings.AUTH_USER_MODEL)),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='plans.trainingplan')),
            ],
            options={
                'db_table': 'plan_assignments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkoutLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('logged_date', models.DateField()),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('partial', 'Partial'), ('skipped', 'Skipped')], max_length=20)),
                ('perceived_effort_rpe', models.IntegerField(blank=True, null=True)),
                ('athlete_notes', models.TextField(blank=True, null=True)),
                ('source', models.CharField(default='manual', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='plans.planassignment')),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_logs', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='plans.session')),
            ],
            options={
                'db_table': 'workout_logs',
                'ordering': ['-logged_date'],
            },
        ),
    ]
