# Generated by Django 5.2.14 on 2026-05-19 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0003_sessionreminderdelivery'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='sessionreminderdelivery',
            new_name='session_rem_athlete_630240_idx',
            old_name='session_rem_athlete_7483c0_idx',
        ),
        migrations.RenameIndex(
            model_name='sessionreminderdelivery',
            new_name='session_rem_reminde_9f312a_idx',
            old_name='session_rem_reminde_34ba9b_idx',
        ),
    ]
