# Generated by Django 5.2.14 on 2026-05-17 16:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plans', '0002_workoutlog_actual_distance_m_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SetLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.IntegerField()),
                ('repetitions_completed', models.IntegerField(blank=True, null=True)),
                ('distance_m', models.IntegerField(blank=True, null=True)),
                ('stroke', models.CharField(blank=True, choices=[('freestyle', 'Freestyle'), ('backstroke', 'Backstroke'), ('breaststroke', 'Breaststroke'), ('butterfly', 'Butterfly'), ('im', 'Individual Medley'), ('choice', 'Choice')], max_length=20, null=True)),
                ('avg_pace_per_100m', models.CharField(blank=True, max_length=10, null=True)),
                ('avg_hr_bpm', models.IntegerField(blank=True, null=True)),
                ('max_hr_bpm', models.IntegerField(blank=True, null=True)),
                ('avg_swolf', models.FloatField(blank=True, null=True)),
                ('avg_stroke_rate_spm', models.FloatField(blank=True, null=True)),
                ('avg_stroke_count_per_length', models.FloatField(blank=True, null=True)),
                ('rest_taken_seconds', models.IntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('set_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='set_logs', to='plans.sessionset')),
                ('workout_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='set_logs', to='plans.workoutlog')),
            ],
            options={
                'db_table': 'set_logs',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='StravaRawActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('strava_activity_id', models.BigIntegerField(unique=True)),
                ('raw_payload', models.JSONField()),
                ('processed', models.BooleanField(default=False)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strava_raw_activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'strava_raw_activities',
            },
        ),
        migrations.CreateModel(
            name='StravaSync',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('strava_athlete_id', models.BigIntegerField(unique=True)),
                ('access_token', models.TextField()),
                ('refresh_token', models.TextField()),
                ('token_expires_at', models.DateTimeField()),
                ('scope', models.CharField(default='activity:read_all', max_length=200)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('sync_status', models.CharField(choices=[('idle', 'Idle'), ('syncing', 'Syncing'), ('error', 'Error')], default='idle', max_length=20)),
                ('last_error', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('athlete', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='strava_sync', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'strava_syncs',
            },
        ),
        migrations.CreateModel(
            name='MetricSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('logged_date', models.DateField()),
                ('metric_type', models.CharField(choices=[('hr_avg', 'Avg HR'), ('hr_max', 'Max HR'), ('pace_avg', 'Avg Pace'), ('swolf_avg', 'Avg SWOLF'), ('stroke_rate', 'Stroke Rate'), ('distance', 'Distance'), ('duration', 'Duration'), ('rpe', 'RPE'), ('compliance_score', 'Compliance Score')], max_length=30)),
                ('value', models.FloatField()),
                ('unit', models.CharField(max_length=20)),
                ('computed_at', models.DateTimeField(auto_now_add=True)),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metric_snapshots', to=settings.AUTH_USER_MODEL)),
                ('workout_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metric_snapshots', to='plans.workoutlog')),
            ],
            options={
                'db_table': 'metric_snapshots',
                'indexes': [models.Index(fields=['athlete', 'metric_type', 'logged_date'], name='metric_snap_athlete_a29c2c_idx')],
            },
        ),
    ]
