# Generated by Django 5.2.14 on 2026-05-15 12:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CoachAthleteRelationship',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('paused', 'Paused'), ('removed', 'Removed')], default='pending', max_length=10)),
                ('invite_token_hash', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('invite_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('invited_at', models.DateTimeField(blank=True, null=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('athlete', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coaches', to=settings.AUTH_USER_MODEL)),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coached_athletes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'coach_athlete_relationships',
                'unique_together': {('coach', 'athlete')},
            },
        ),
    ]
