/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as AppTeamRouteImport } from './routes/_app/team'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppPlansRouteImport } from './routes/_app/plans'
import { Route as AppPlanRouteImport } from './routes/_app/plan'
import { Route as AppMetricsRouteImport } from './routes/_app/metrics'
import { Route as AppInsightsRouteImport } from './routes/_app/insights'
import { Route as AppSettingsIndexRouteImport } from './routes/_app/settings.index'
import { Route as AppPlansIndexRouteImport } from './routes/_app/plans.index'
import { Route as AppMetricsIndexRouteImport } from './routes/_app/metrics.index'
import { Route as AppInsightsIndexRouteImport } from './routes/_app/insights.index'
import { Route as AppSettingsDevicesRouteImport } from './routes/_app/settings.devices'
import { Route as AppPlansIdRouteImport } from './routes/_app/plans.$id'
import { Route as AppMetricsTeamRouteImport } from './routes/_app/metrics.team'
import { Route as AppInsightsDigestRouteImport } from './routes/_app/insights.digest'
import { Route as AppInsightsIdRouteImport } from './routes/_app/insights.$id'
import { Route as AppActivitiesWorkoutLogIdRouteImport } from './routes/_app/activities.$workoutLogId'
import { Route as AppMetricsAthleteAthleteIdRouteImport } from './routes/_app/metrics.athlete.$athleteId'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTeamRoute = AppTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppPlansRoute = AppPlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppPlanRoute = AppPlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppMetricsRoute = AppMetricsRouteImport.update({
  id: '/metrics',
  path: '/metrics',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppInsightsRoute = AppInsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSettingsIndexRoute = AppSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppPlansIndexRoute = AppPlansIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppPlansRoute,
} as any)
const AppMetricsIndexRoute = AppMetricsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppMetricsRoute,
} as any)
const AppInsightsIndexRoute = AppInsightsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppInsightsRoute,
} as any)
const AppSettingsDevicesRoute = AppSettingsDevicesRouteImport.update({
  id: '/devices',
  path: '/devices',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppPlansIdRoute = AppPlansIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppPlansRoute,
} as any)
const AppMetricsTeamRoute = AppMetricsTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AppMetricsRoute,
} as any)
const AppInsightsDigestRoute = AppInsightsDigestRouteImport.update({
  id: '/digest',
  path: '/digest',
  getParentRoute: () => AppInsightsRoute,
} as any)
const AppInsightsIdRoute = AppInsightsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppInsightsRoute,
} as any)
const AppActivitiesWorkoutLogIdRoute =
  AppActivitiesWorkoutLogIdRouteImport.update({
    id: '/activities/$workoutLogId',
    path: '/activities/$workoutLogId',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppMetricsAthleteAthleteIdRoute =
  AppMetricsAthleteAthleteIdRouteImport.update({
    id: '/athlete/$athleteId',
    path: '/athlete/$athleteId',
    getParentRoute: () => AppMetricsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/register': typeof RegisterRoute
  '/insights': typeof AppInsightsRouteWithChildren
  '/metrics': typeof AppMetricsRouteWithChildren
  '/plan': typeof AppPlanRoute
  '/plans': typeof AppPlansRouteWithChildren
  '/settings': typeof AppSettingsRouteWithChildren
  '/team': typeof AppTeamRoute
  '/invite/$token': typeof InviteTokenRoute
  '/activities/$workoutLogId': typeof AppActivitiesWorkoutLogIdRoute
  '/insights/$id': typeof AppInsightsIdRoute
  '/insights/digest': typeof AppInsightsDigestRoute
  '/metrics/team': typeof AppMetricsTeamRoute
  '/plans/$id': typeof AppPlansIdRoute
  '/settings/devices': typeof AppSettingsDevicesRoute
  '/insights/': typeof AppInsightsIndexRoute
  '/metrics/': typeof AppMetricsIndexRoute
  '/plans/': typeof AppPlansIndexRoute
  '/settings/': typeof AppSettingsIndexRoute
  '/metrics/athlete/$athleteId': typeof AppMetricsAthleteAthleteIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/register': typeof RegisterRoute
  '/plan': typeof AppPlanRoute
  '/team': typeof AppTeamRoute
  '/invite/$token': typeof InviteTokenRoute
  '/activities/$workoutLogId': typeof AppActivitiesWorkoutLogIdRoute
  '/insights/$id': typeof AppInsightsIdRoute
  '/insights/digest': typeof AppInsightsDigestRoute
  '/metrics/team': typeof AppMetricsTeamRoute
  '/plans/$id': typeof AppPlansIdRoute
  '/settings/devices': typeof AppSettingsDevicesRoute
  '/insights': typeof AppInsightsIndexRoute
  '/metrics': typeof AppMetricsIndexRoute
  '/plans': typeof AppPlansIndexRoute
  '/settings': typeof AppSettingsIndexRoute
  '/metrics/athlete/$athleteId': typeof AppMetricsAthleteAthleteIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/register': typeof RegisterRoute
  '/_app/insights': typeof AppInsightsRouteWithChildren
  '/_app/metrics': typeof AppMetricsRouteWithChildren
  '/_app/plan': typeof AppPlanRoute
  '/_app/plans': typeof AppPlansRouteWithChildren
  '/_app/settings': typeof AppSettingsRouteWithChildren
  '/_app/team': typeof AppTeamRoute
  '/invite/$token': typeof InviteTokenRoute
  '/_app/activities/$workoutLogId': typeof AppActivitiesWorkoutLogIdRoute
  '/_app/insights/$id': typeof AppInsightsIdRoute
  '/_app/insights/digest': typeof AppInsightsDigestRoute
  '/_app/metrics/team': typeof AppMetricsTeamRoute
  '/_app/plans/$id': typeof AppPlansIdRoute
  '/_app/settings/devices': typeof AppSettingsDevicesRoute
  '/_app/insights/': typeof AppInsightsIndexRoute
  '/_app/metrics/': typeof AppMetricsIndexRoute
  '/_app/plans/': typeof AppPlansIndexRoute
  '/_app/settings/': typeof AppSettingsIndexRoute
  '/_app/metrics/athlete/$athleteId': typeof AppMetricsAthleteAthleteIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/onboarding'
    | '/register'
    | '/insights'
    | '/metrics'
    | '/plan'
    | '/plans'
    | '/settings'
    | '/team'
    | '/invite/$token'
    | '/activities/$workoutLogId'
    | '/insights/$id'
    | '/insights/digest'
    | '/metrics/team'
    | '/plans/$id'
    | '/settings/devices'
    | '/insights/'
    | '/metrics/'
    | '/plans/'
    | '/settings/'
    | '/metrics/athlete/$athleteId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/onboarding'
    | '/register'
    | '/plan'
    | '/team'
    | '/invite/$token'
    | '/activities/$workoutLogId'
    | '/insights/$id'
    | '/insights/digest'
    | '/metrics/team'
    | '/plans/$id'
    | '/settings/devices'
    | '/insights'
    | '/metrics'
    | '/plans'
    | '/settings'
    | '/metrics/athlete/$athleteId'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/onboarding'
    | '/register'
    | '/_app/insights'
    | '/_app/metrics'
    | '/_app/plan'
    | '/_app/plans'
    | '/_app/settings'
    | '/_app/team'
    | '/invite/$token'
    | '/_app/activities/$workoutLogId'
    | '/_app/insights/$id'
    | '/_app/insights/digest'
    | '/_app/metrics/team'
    | '/_app/plans/$id'
    | '/_app/settings/devices'
    | '/_app/insights/'
    | '/_app/metrics/'
    | '/_app/plans/'
    | '/_app/settings/'
    | '/_app/metrics/athlete/$athleteId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  RegisterRoute: typeof RegisterRoute
  InviteTokenRoute: typeof InviteTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/team': {
      id: '/_app/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof AppTeamRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/plans': {
      id: '/_app/plans'
      path: '/plans'
      fullPath: '/plans'
      preLoaderRoute: typeof AppPlansRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/plan': {
      id: '/_app/plan'
      path: '/plan'
      fullPath: '/plan'
      preLoaderRoute: typeof AppPlanRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/metrics': {
      id: '/_app/metrics'
      path: '/metrics'
      fullPath: '/metrics'
      preLoaderRoute: typeof AppMetricsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/insights': {
      id: '/_app/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof AppInsightsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/settings/': {
      id: '/_app/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AppSettingsIndexRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/plans/': {
      id: '/_app/plans/'
      path: '/'
      fullPath: '/plans/'
      preLoaderRoute: typeof AppPlansIndexRouteImport
      parentRoute: typeof AppPlansRoute
    }
    '/_app/metrics/': {
      id: '/_app/metrics/'
      path: '/'
      fullPath: '/metrics/'
      preLoaderRoute: typeof AppMetricsIndexRouteImport
      parentRoute: typeof AppMetricsRoute
    }
    '/_app/insights/': {
      id: '/_app/insights/'
      path: '/'
      fullPath: '/insights/'
      preLoaderRoute: typeof AppInsightsIndexRouteImport
      parentRoute: typeof AppInsightsRoute
    }
    '/_app/settings/devices': {
      id: '/_app/settings/devices'
      path: '/devices'
      fullPath: '/settings/devices'
      preLoaderRoute: typeof AppSettingsDevicesRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/plans/$id': {
      id: '/_app/plans/$id'
      path: '/$id'
      fullPath: '/plans/$id'
      preLoaderRoute: typeof AppPlansIdRouteImport
      parentRoute: typeof AppPlansRoute
    }
    '/_app/metrics/team': {
      id: '/_app/metrics/team'
      path: '/team'
      fullPath: '/metrics/team'
      preLoaderRoute: typeof AppMetricsTeamRouteImport
      parentRoute: typeof AppMetricsRoute
    }
    '/_app/insights/digest': {
      id: '/_app/insights/digest'
      path: '/digest'
      fullPath: '/insights/digest'
      preLoaderRoute: typeof AppInsightsDigestRouteImport
      parentRoute: typeof AppInsightsRoute
    }
    '/_app/insights/$id': {
      id: '/_app/insights/$id'
      path: '/$id'
      fullPath: '/insights/$id'
      preLoaderRoute: typeof AppInsightsIdRouteImport
      parentRoute: typeof AppInsightsRoute
    }
    '/_app/activities/$workoutLogId': {
      id: '/_app/activities/$workoutLogId'
      path: '/activities/$workoutLogId'
      fullPath: '/activities/$workoutLogId'
      preLoaderRoute: typeof AppActivitiesWorkoutLogIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/metrics/athlete/$athleteId': {
      id: '/_app/metrics/athlete/$athleteId'
      path: '/athlete/$athleteId'
      fullPath: '/metrics/athlete/$athleteId'
      preLoaderRoute: typeof AppMetricsAthleteAthleteIdRouteImport
      parentRoute: typeof AppMetricsRoute
    }
  }
}

interface AppInsightsRouteChildren {
  AppInsightsIdRoute: typeof AppInsightsIdRoute
  AppInsightsDigestRoute: typeof AppInsightsDigestRoute
  AppInsightsIndexRoute: typeof AppInsightsIndexRoute
}

const AppInsightsRouteChildren: AppInsightsRouteChildren = {
  AppInsightsIdRoute: AppInsightsIdRoute,
  AppInsightsDigestRoute: AppInsightsDigestRoute,
  AppInsightsIndexRoute: AppInsightsIndexRoute,
}

const AppInsightsRouteWithChildren = AppInsightsRoute._addFileChildren(
  AppInsightsRouteChildren,
)

interface AppMetricsRouteChildren {
  AppMetricsTeamRoute: typeof AppMetricsTeamRoute
  AppMetricsIndexRoute: typeof AppMetricsIndexRoute
  AppMetricsAthleteAthleteIdRoute: typeof AppMetricsAthleteAthleteIdRoute
}

const AppMetricsRouteChildren: AppMetricsRouteChildren = {
  AppMetricsTeamRoute: AppMetricsTeamRoute,
  AppMetricsIndexRoute: AppMetricsIndexRoute,
  AppMetricsAthleteAthleteIdRoute: AppMetricsAthleteAthleteIdRoute,
}

const AppMetricsRouteWithChildren = AppMetricsRoute._addFileChildren(
  AppMetricsRouteChildren,
)

interface AppPlansRouteChildren {
  AppPlansIdRoute: typeof AppPlansIdRoute
  AppPlansIndexRoute: typeof AppPlansIndexRoute
}

const AppPlansRouteChildren: AppPlansRouteChildren = {
  AppPlansIdRoute: AppPlansIdRoute,
  AppPlansIndexRoute: AppPlansIndexRoute,
}

const AppPlansRouteWithChildren = AppPlansRoute._addFileChildren(
  AppPlansRouteChildren,
)

interface AppSettingsRouteChildren {
  AppSettingsDevicesRoute: typeof AppSettingsDevicesRoute
  AppSettingsIndexRoute: typeof AppSettingsIndexRoute
}

const AppSettingsRouteChildren: AppSettingsRouteChildren = {
  AppSettingsDevicesRoute: AppSettingsDevicesRoute,
  AppSettingsIndexRoute: AppSettingsIndexRoute,
}

const AppSettingsRouteWithChildren = AppSettingsRoute._addFileChildren(
  AppSettingsRouteChildren,
)

interface AppRouteRouteChildren {
  AppInsightsRoute: typeof AppInsightsRouteWithChildren
  AppMetricsRoute: typeof AppMetricsRouteWithChildren
  AppPlanRoute: typeof AppPlanRoute
  AppPlansRoute: typeof AppPlansRouteWithChildren
  AppSettingsRoute: typeof AppSettingsRouteWithChildren
  AppTeamRoute: typeof AppTeamRoute
  AppActivitiesWorkoutLogIdRoute: typeof AppActivitiesWorkoutLogIdRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppInsightsRoute: AppInsightsRouteWithChildren,
  AppMetricsRoute: AppMetricsRouteWithChildren,
  AppPlanRoute: AppPlanRoute,
  AppPlansRoute: AppPlansRouteWithChildren,
  AppSettingsRoute: AppSettingsRouteWithChildren,
  AppTeamRoute: AppTeamRoute,
  AppActivitiesWorkoutLogIdRoute: AppActivitiesWorkoutLogIdRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  RegisterRoute: RegisterRoute,
  InviteTokenRoute: InviteTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
